components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
          format: email
          description: Email for the user, needs to be unique.
      example:
        name: jjeongryu
        email: totw2020@korea.ac.kr
